server:
  port: 8000
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
      - id: pension-detail
        uri: lb://pension-detail
        predicates:
        - Path=/pension/**
      - id: pension-process
        uri: lb://pension-process
        predicates:
        - Path="/pension/**" 